### ISSUE TITLE
Implement Facebook friend invitation (And invitations in general)

### ISSUE THREAD

**Issue by huyouare** [huyouare/Duke-Study-Group#9]

**Comment by JustinLovesCompsci** [comment]
Just read this piece of info "Apps are no longer able to retrieve the full list of a user’s friends (only those friends who have specifically authorized your app using the user_friends permission). This has been confirmed by Facebook as ‘by design’."
So I guess user can only invite Facebook friends who have already authorized Facebook login to the app, right? What about those who login with email? Then do we even need the login with email option?

**Comment by JustinLovesCompsci** [comment]
By tapping an add button in group settings, a user can specify a name and search through the whole list of duke community, like Duke directory. Then the user can invite a Dukie

**Comment by JustinLovesCompsci** [comment]
#38
